/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.View;

import fatec.poo.control.Conexao;
import fatec.poo.control.DaoAluno;
import fatec.poo.model.Aluno;
import javax.swing.JOptionPane;

/**
 * Felipe Camargo RA: 0030481813029 Vinicius Bistão RA: 0030481813011
 */
public class GuiAluno extends javax.swing.JFrame {

    /**
     * Creates new form GuiAluno
     */
    public GuiAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSair1 = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        lblCPF = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lblRG = new javax.swing.JLabel();
        frmtdtxtCPF = new javax.swing.JFormattedTextField();
        txtNome = new javax.swing.JTextField();
        frmtdtxtDtNasc = new javax.swing.JFormattedTextField();
        lblDtNasc = new javax.swing.JLabel();
        cbxSexo = new javax.swing.JComboBox<>();
        lblEstadoCivil = new javax.swing.JLabel();
        cbxEstadoCivil = new javax.swing.JComboBox<>();
        lblEscolaridade = new javax.swing.JLabel();
        cbxEscolaridade = new javax.swing.JComboBox<>();
        txtEndereco = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        frmtdtxtRG = new javax.swing.JFormattedTextField();
        txtEmail = new javax.swing.JTextField();
        lblNum = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblCPF1 = new javax.swing.JLabel();
        frmtdtxtCEP = new javax.swing.JFormattedTextField();
        lblTelRes = new javax.swing.JLabel();
        frmtdtxtTelRes = new javax.swing.JFormattedTextField();
        lblCelular = new javax.swing.JLabel();
        frmtdtxtCelular = new javax.swing.JFormattedTextField();
        cbxEstado = new javax.swing.JComboBox<>();
        lblCidade1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnSair1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/View/icon/exit.png"))); // NOI18N
        btnSair1.setText("Sair");
        btnSair1.setName("btnSair"); // NOI18N
        btnSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair1ActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/View/icon/rem.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.setName("btnExcluir"); // NOI18N
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/View/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.setName("btnAlterar"); // NOI18N
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/View/icon/add.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.setName("btnInserir"); // NOI18N
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/View/icon/pesq.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.setName("btnConsultar"); // NOI18N
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        lblCPF.setText("CPF");
        lblCPF.setName("lblCPF"); // NOI18N

        lblNome.setText("Nome");
        lblNome.setName("lblNome"); // NOI18N

        lblEmail.setText("Email");
        lblEmail.setName("lblEmail"); // NOI18N

        lblSexo.setText("Sexo");
        lblSexo.setName("lblSexo"); // NOI18N

        lblEndereco.setText("Endereço");
        lblEndereco.setName("lblEndereco"); // NOI18N

        lblBairro.setText("Bairro");
        lblBairro.setName("lblBairro"); // NOI18N

        lblCidade.setText("Cidade");
        lblCidade.setName("lblCidade"); // NOI18N

        lblRG.setText("RG");
        lblRG.setName("lblRG"); // NOI18N

        try {
            frmtdtxtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        frmtdtxtCPF.setName("frmtdtxtCPF"); // NOI18N

        txtNome.setEnabled(false);
        txtNome.setName("txtNome"); // NOI18N

        try {
            frmtdtxtDtNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        frmtdtxtDtNasc.setEnabled(false);
        frmtdtxtDtNasc.setName("frmtdtxtDtNasc"); // NOI18N

        lblDtNasc.setText("Data Nasc.");
        lblDtNasc.setName("lblDtNasc"); // NOI18N

        cbxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "S" }));
        cbxSexo.setEnabled(false);
        cbxSexo.setName("cbxSexo"); // NOI18N

        lblEstadoCivil.setText("Estado Civil");
        lblEstadoCivil.setName("lblEstadoCivil"); // NOI18N

        cbxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro", "Casado" }));
        cbxEstadoCivil.setEnabled(false);
        cbxEstadoCivil.setName("cbxEstadoCivil"); // NOI18N

        lblEscolaridade.setText("Escolaridade");
        lblEscolaridade.setName("lblEscolaridade"); // NOI18N

        cbxEscolaridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Médio", "Fundamental", "Supeior" }));
        cbxEscolaridade.setEnabled(false);
        cbxEscolaridade.setName("cbxEscolaridade"); // NOI18N
        cbxEscolaridade.setVerifyInputWhenFocusTarget(false);

        txtEndereco.setEnabled(false);
        txtEndereco.setName("txtEndereco"); // NOI18N

        txtBairro.setEnabled(false);
        txtBairro.setName("txtBairro"); // NOI18N

        txtCidade.setEnabled(false);
        txtCidade.setName("txtCidade"); // NOI18N

        try {
            frmtdtxtRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        frmtdtxtRG.setEnabled(false);
        frmtdtxtRG.setName("frmtdtxtRG"); // NOI18N

        txtEmail.setEnabled(false);
        txtEmail.setName("txtEmail"); // NOI18N

        lblNum.setText("Nº");
        lblNum.setName("lblNum"); // NOI18N

        txtNumero.setEnabled(false);
        txtNumero.setName("txtEmail"); // NOI18N

        lblCPF1.setText("CEP");
        lblCPF1.setName("lblCPF"); // NOI18N

        try {
            frmtdtxtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        frmtdtxtCEP.setEnabled(false);
        frmtdtxtCEP.setName("frmtdtxtCEP"); // NOI18N

        lblTelRes.setText("Tel. Res.");
        lblTelRes.setName("lblTelRes"); // NOI18N

        try {
            frmtdtxtTelRes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        frmtdtxtTelRes.setEnabled(false);
        frmtdtxtTelRes.setName("frmtdtxtTelRes"); // NOI18N

        lblCelular.setText("Celular");
        lblCelular.setName("lblCelular"); // NOI18N

        try {
            frmtdtxtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        frmtdtxtCelular.setEnabled(false);
        frmtdtxtCelular.setName("frmtdtxtCelular"); // NOI18N

        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cbxEstado.setEnabled(false);
        cbxEstado.setName("cbxEscolaridade"); // NOI18N
        cbxEstado.setVerifyInputWhenFocusTarget(false);

        lblCidade1.setText("Estado");
        lblCidade1.setName("lblCidade"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblSexo)
                        .addGap(18, 18, 18)
                        .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(lblEstadoCivil)
                        .addGap(18, 18, 18)
                        .addComponent(cbxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(lblEscolaridade)
                        .addGap(18, 18, 18)
                        .addComponent(cbxEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEndereco)
                        .addGap(18, 18, 18)
                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(lblNum)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblBairro)
                        .addGap(18, 18, 18)
                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(lblCPF1)
                        .addGap(18, 18, 18)
                        .addComponent(frmtdtxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblCidade)
                        .addGap(18, 18, 18)
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(lblCidade1)
                        .addGap(18, 18, 18)
                        .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(lblTelRes)
                        .addGap(18, 18, 18)
                        .addComponent(frmtdtxtTelRes))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblRG)
                        .addGap(18, 18, 18)
                        .addComponent(frmtdtxtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(226, 226, 226)
                        .addComponent(lblCelular)
                        .addGap(18, 18, 18)
                        .addComponent(frmtdtxtCelular))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblEmail)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnConsultar)
                        .addGap(6, 6, 6)
                        .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnSair1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNome)
                            .addComponent(lblCPF))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(lblDtNasc)
                                .addGap(10, 10, 10)
                                .addComponent(frmtdtxtDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(frmtdtxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblCPF))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(frmtdtxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frmtdtxtDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addComponent(lblDtNasc))))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSexo)
                            .addComponent(lblEstadoCivil)
                            .addComponent(lblEscolaridade))))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEndereco)
                            .addComponent(lblNum))))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frmtdtxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBairro)
                            .addComponent(lblCPF1))))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCidade)
                        .addComponent(lblCidade1)
                        .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblTelRes))
                    .addComponent(frmtdtxtTelRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lblRG))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lblCelular))
                            .addComponent(frmtdtxtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(frmtdtxtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultar)
                    .addComponent(btnInserir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair1))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        conexao.fecharConexao();
        dispose();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao("SYSTEM", "123");
        conexao.setDriver("oracle.jdbc.driver.OracleDriver");
        conexao.setConnectionString("jdbc:oracle:thin:@localhost:1521:xe");
        daoAluno = new DaoAluno(conexao.conectar());      
    }//GEN-LAST:event_formWindowOpened

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        aluno = null;
        aluno = daoAluno.consultar(frmtdtxtCPF.getText());

        if (aluno == null) {
            frmtdtxtCPF.setEnabled(false);
            txtNome.setEnabled(true);
            frmtdtxtDtNasc.setEnabled(true);
            cbxSexo.setEnabled(true);
            cbxEscolaridade.setEnabled(true);
            cbxEstadoCivil.setEnabled(true);
            txtEndereco.setEnabled(true);
            txtNumero.setEnabled(true);
            txtBairro.setEnabled(true);
            frmtdtxtCEP.setEnabled(true);
            txtCidade.setEnabled(true);
            cbxEstado.setEnabled(true);
            frmtdtxtTelRes.setEnabled(true);
            frmtdtxtRG.setEnabled(true);
            frmtdtxtCelular.setEnabled(true);
            txtEmail.setEnabled(true);
            txtNome.requestFocus();

            btnConsultar.setEnabled(false);
            btnInserir.setEnabled(true);
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);
        } else {
            txtNome.setText(aluno.getNome());
            frmtdtxtDtNasc.setText(aluno.getDtNasc());
            cbxSexo.setSelectedItem(aluno.getSexo());
            cbxEscolaridade.setSelectedItem(aluno.getEscolaridade());
            cbxEstadoCivil.setSelectedItem(aluno.getEstadoCivil());
            txtEndereco.setText(aluno.getEndereco());
            txtNumero.setText(Integer.toString(aluno.getNumero()));
            txtBairro.setText(aluno.getBairro());
            frmtdtxtCEP.setText(aluno.getCep());
            txtCidade.setText(aluno.getCidade());
            cbxEstado.setSelectedItem(aluno.getEstado());
            frmtdtxtTelRes.setText(aluno.getTelRes());
            frmtdtxtRG.setText(aluno.getRg());
            frmtdtxtCelular.setText(aluno.getCelular());
            txtEmail.setText(aluno.getEmail());
            txtNome.requestFocus();

            frmtdtxtCPF.setEnabled(false);
            txtNome.setEnabled(true);
            frmtdtxtDtNasc.setEnabled(true);
            cbxSexo.setEnabled(true);
            cbxEscolaridade.setEnabled(true);
            cbxEstadoCivil.setEnabled(true);
            txtEndereco.setEnabled(true);
            txtNumero.setEnabled(true);
            txtBairro.setEnabled(true);
            frmtdtxtCEP.setEnabled(true);
            txtCidade.setEnabled(true);
            cbxEstado.setEnabled(true);
            frmtdtxtTelRes.setEnabled(true);
            frmtdtxtRG.setEnabled(true);
            frmtdtxtCelular.setEnabled(true);
            txtEmail.setEnabled(true);
            txtNome.requestFocus();

            btnConsultar.setEnabled(false);
            btnInserir.setEnabled(false);
            btnAlterar.setEnabled(true);
            btnExcluir.setEnabled(true);
        }
        
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        aluno = new Aluno(frmtdtxtCPF.getText(), txtNome.getText());

        aluno.setDtNasc(frmtdtxtDtNasc.getText());
        aluno.setEndereco(txtEndereco.getText());
        aluno.setNumero(Integer.parseInt(txtNumero.getText()));
        aluno.setBairro(txtBairro.getText());
        aluno.setCidade(txtCidade.getText());
        aluno.setEstado(String.valueOf(cbxEstado.getSelectedItem()));
        aluno.setCep(frmtdtxtCEP.getText());        
        aluno.setTelRes(frmtdtxtTelRes.getText());
        aluno.setCelular(frmtdtxtCelular.getText());
        aluno.setSexo(String.valueOf(cbxSexo.getSelectedItem()));
        aluno.setEstadoCivil(String.valueOf(cbxEstadoCivil.getSelectedItem()));
        aluno.setRg(frmtdtxtRG.getText());        
        aluno.setEmail(txtEmail.getText());
        aluno.setEscolaridade(String.valueOf(cbxEscolaridade.getSelectedItem()));                   
        daoAluno.inserir(aluno);

        frmtdtxtCPF.setText("");
        txtNome.setText("");
        frmtdtxtDtNasc.setText("");
        cbxSexo.setSelectedItem("");
        cbxEstadoCivil.setSelectedItem("");
        cbxEscolaridade.setSelectedItem("");
        txtEndereco.setText("");
        txtNumero.setText("");
        txtBairro.setText("");
        frmtdtxtCEP.setText("");
        txtCidade.setText("");
        cbxEstado.setSelectedItem("");
        frmtdtxtTelRes.setText("");
        frmtdtxtRG.setText("");
        frmtdtxtCelular.setText("");
        txtEmail.setText("");

        frmtdtxtCPF.setEnabled(true);
        txtNome.setEnabled(false);
        frmtdtxtDtNasc.setEnabled(false);
        cbxSexo.setEnabled(false);
        cbxEstadoCivil.setEnabled(false);
        cbxEscolaridade.setEnabled(false);
        txtEndereco.setEnabled(false);
        txtNumero.setEnabled(false);
        txtBairro.setEnabled(false);
        frmtdtxtCEP.setEnabled(false);
        txtCidade.setEnabled(false);
        cbxEstado.setEnabled(false);
        frmtdtxtTelRes.setEnabled(false);
        frmtdtxtRG.setEnabled(false);
        frmtdtxtCelular.setEnabled(false);
        txtEmail.setEnabled(false);
        frmtdtxtCPF.requestFocus();

        btnInserir.setEnabled(false);
        btnConsultar.setEnabled(true);       
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Alteração?") == 0) {//Sim
            aluno.setNome(txtNome.getText());
            aluno.setDtNasc(frmtdtxtDtNasc.getText());
            aluno.setSexo(String.valueOf(cbxSexo.getSelectedItem()));
            aluno.setEstadoCivil(String.valueOf(cbxEstadoCivil.getSelectedItem()));
            aluno.setEscolaridade(String.valueOf(cbxEscolaridade.getSelectedItem()));
            aluno.setEndereco(txtEndereco.getText());
            aluno.setNumero(Integer.parseInt(txtNumero.getText()));
            aluno.setBairro(txtBairro.getText());
            aluno.setCep(frmtdtxtCEP.getText());
            aluno.setCidade(txtCidade.getText());
            aluno.setEstado(String.valueOf(cbxEstado.getSelectedItem()));
            aluno.setTelRes(frmtdtxtTelRes.getText());
            aluno.setRg(frmtdtxtRG.getText());
            aluno.setCelular(frmtdtxtCelular.getText());
            aluno.setEmail(txtEmail.getText());
            daoAluno.alterar(aluno);
        }

        frmtdtxtCPF.setText("");
        txtNome.setText("");
        frmtdtxtDtNasc.setText("");
        cbxSexo.setSelectedItem("");
        cbxEstadoCivil.setSelectedItem("");
        cbxEscolaridade.setSelectedItem("");
        txtEndereco.setText("");
        txtNumero.setText("");
        txtBairro.setText("");
        frmtdtxtCEP.setText("");
        txtCidade.setText("");
        cbxEstado.setSelectedItem("");
        frmtdtxtTelRes.setText("");
        frmtdtxtRG.setText("");
        frmtdtxtCelular.setText("");
        txtEmail.setText("");

        frmtdtxtCPF.setEnabled(true);
        txtNome.setEnabled(false);
        frmtdtxtDtNasc.setEnabled(false);
        cbxSexo.setEnabled(false);
        cbxEstadoCivil.setEnabled(false);
        cbxEscolaridade.setEnabled(false);
        txtEndereco.setEnabled(false);
        txtNumero.setEnabled(false);
        txtBairro.setEnabled(false);
        frmtdtxtCEP.setEnabled(false);
        txtCidade.setEnabled(false);
        cbxEstado.setEnabled(false);
        frmtdtxtTelRes.setEnabled(false);
        frmtdtxtRG.setEnabled(false);
        frmtdtxtCelular.setEnabled(false);
        txtEmail.setEnabled(false);
        frmtdtxtCPF.requestFocus();

        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
      
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Exclusão?") == 0) {
            daoAluno.excluir(aluno);

            frmtdtxtCPF.setText("");
            txtNome.setText("");
            frmtdtxtDtNasc.setText("");
            cbxSexo.setSelectedItem("");
            cbxEstadoCivil.setSelectedItem("");
            cbxEscolaridade.setSelectedItem("");
            txtEndereco.setText("");
            txtNumero.setText("");
            txtBairro.setText("");
            frmtdtxtCEP.setText("");
            txtCidade.setText("");
            cbxEstado.setSelectedItem("");
            frmtdtxtTelRes.setText("");
            frmtdtxtRG.setText("");
            frmtdtxtCelular.setText("");
            txtEmail.setText("");

            frmtdtxtCPF.setEnabled(true);
            txtNome.setEnabled(false);
            frmtdtxtDtNasc.setEnabled(false);
            cbxSexo.setEnabled(false);
            cbxEstadoCivil.setEnabled(false);
            cbxEscolaridade.setEnabled(false);
            txtEndereco.setEnabled(false);
            txtNumero.setEnabled(false);
            txtBairro.setEnabled(false);
            frmtdtxtCEP.setEnabled(false);
            txtCidade.setEnabled(false);
            cbxEstado.setEnabled(false);
            frmtdtxtTelRes.setEnabled(false);
            frmtdtxtRG.setEnabled(false);
            frmtdtxtCelular.setEnabled(false);
            txtEmail.setEnabled(false);
            frmtdtxtCPF.requestFocus();

            btnConsultar.setEnabled(true);
            btnInserir.setEnabled(false);
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false); 
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSair1ActionPerformed
        dispose();
    }//GEN-LAST:event_btnSair1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair1;
    private javax.swing.JComboBox<String> cbxEscolaridade;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JComboBox<String> cbxEstadoCivil;
    private javax.swing.JComboBox<String> cbxSexo;
    private javax.swing.JFormattedTextField frmtdtxtCEP;
    private javax.swing.JFormattedTextField frmtdtxtCPF;
    private javax.swing.JFormattedTextField frmtdtxtCelular;
    private javax.swing.JFormattedTextField frmtdtxtDtNasc;
    private javax.swing.JFormattedTextField frmtdtxtRG;
    private javax.swing.JFormattedTextField frmtdtxtTelRes;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCPF1;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCidade1;
    private javax.swing.JLabel lblDtNasc;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEscolaridade;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelRes;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
    private Conexao conexao = null;
    private Aluno aluno = null;
    private DaoAluno daoAluno = null;
}
