/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.View;

import fatec.poo.control.Conexao;
import fatec.poo.control.DaoCurso;
import fatec.poo.model.Curso;
import javax.swing.JOptionPane;

/**
 * Felipe Camargo RA: 0030481813029 Vinicius Bistão RA: 0030481813011
 */
public class GuiCurso extends javax.swing.JFrame {

    /**
     * Creates new form GuiCurso
     */
    public GuiCurso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSiglaCurso = new javax.swing.JLabel();
        lblNomeCurso = new javax.swing.JLabel();
        lblValorCurso = new javax.swing.JLabel();
        lblCargaHoraria = new javax.swing.JLabel();
        lblDtVigencia = new javax.swing.JLabel();
        lblProgramaCurso = new javax.swing.JLabel();
        txtSiglaCurso = new javax.swing.JTextField();
        txtNomeCurso = new javax.swing.JTextField();
        txtCargaHoraria = new javax.swing.JTextField();
        txtValorCurso = new javax.swing.JTextField();
        txtProgramaCurso = new javax.swing.JTextField();
        lblVarHrInstrutor = new javax.swing.JLabel();
        txtValHrInstrutor = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        frmtdtxtDtVigencia = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Curso");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblSiglaCurso.setText("Sigla Curso");
        lblSiglaCurso.setName("lblSiglaCurso"); // NOI18N

        lblNomeCurso.setText("Nome Curso");
        lblNomeCurso.setName("lblNomeCurso"); // NOI18N

        lblValorCurso.setText("Valor Curso");
        lblValorCurso.setName("lblValorCurso"); // NOI18N

        lblCargaHoraria.setText("Carga Horária");
        lblCargaHoraria.setName("lblCargaHoraria"); // NOI18N

        lblDtVigencia.setText("Data de Vigência");
        lblDtVigencia.setName("lblDtVigencia"); // NOI18N

        lblProgramaCurso.setText("Programa do Curso");
        lblProgramaCurso.setName("lblProgramaCurso"); // NOI18N

        txtSiglaCurso.setName("txtSiglaCurso"); // NOI18N

        txtNomeCurso.setEnabled(false);
        txtNomeCurso.setName("txtNomeCurso"); // NOI18N

        txtCargaHoraria.setEnabled(false);
        txtCargaHoraria.setName("txtCargaHoraria"); // NOI18N

        txtValorCurso.setEnabled(false);
        txtValorCurso.setName("txtValorCurso"); // NOI18N

        txtProgramaCurso.setEnabled(false);
        txtProgramaCurso.setName("txtProgramaCurso"); // NOI18N

        lblVarHrInstrutor.setText("Valor Hora Instrutor");
        lblVarHrInstrutor.setName("lblVarHrInstrutor"); // NOI18N

        txtValHrInstrutor.setEnabled(false);
        txtValHrInstrutor.setName("txtValHrInstrutor"); // NOI18N

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/View/icon/pesq.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.setName("btnConsultar"); // NOI18N
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/View/icon/add.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.setName("btnInserir"); // NOI18N
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/View/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.setName("btnAlterar"); // NOI18N
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/View/icon/rem.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.setName("btnExcluir"); // NOI18N
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/View/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setName("btnSair"); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        try {
            frmtdtxtDtVigencia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        frmtdtxtDtVigencia.setEnabled(false);
        frmtdtxtDtVigencia.setName("frmtdtxtDtVigencia"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblProgramaCurso)
                    .addComponent(lblValorCurso)
                    .addComponent(lblCargaHoraria)
                    .addComponent(lblNomeCurso)
                    .addComponent(lblSiglaCurso)
                    .addComponent(btnConsultar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCargaHoraria)
                                    .addComponent(txtValorCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNomeCurso)
                                    .addComponent(txtSiglaCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDtVigencia, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblVarHrInstrutor, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValHrInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(frmtdtxtDtVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtProgramaCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCargaHoraria, txtNomeCurso, txtProgramaCurso});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnConsultar, btnExcluir, btnInserir, btnSair});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSiglaCurso)
                    .addComponent(txtSiglaCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeCurso)
                    .addComponent(txtNomeCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCargaHoraria)
                    .addComponent(lblDtVigencia)
                    .addComponent(frmtdtxtDtVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorCurso)
                    .addComponent(lblVarHrInstrutor)
                    .addComponent(txtValHrInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProgramaCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProgramaCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnInserir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao("SYSTEM", "123");
        conexao.setDriver("oracle.jdbc.driver.OracleDriver");
        conexao.setConnectionString("jdbc:oracle:thin:@localhost:1521:xe");
        daoCurso = new DaoCurso(conexao.conectar());
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        conexao.fecharConexao();
        dispose();
    }//GEN-LAST:event_formWindowClosed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        curso = null;
        curso = daoCurso.consultar(txtSiglaCurso.getText());

        if (curso == null) {
            txtSiglaCurso.setEnabled(false);
            txtNomeCurso.setEnabled(true);
            txtNomeCurso.requestFocus();
            txtCargaHoraria.setEnabled(true);
            txtValHrInstrutor.setEnabled(true);
            txtProgramaCurso.setEnabled(true);
            frmtdtxtDtVigencia.setEnabled(true);
            txtValorCurso.setEnabled(true);

            btnConsultar.setEnabled(false);
            btnInserir.setEnabled(true);
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(true);
            btnSair.setEnabled(true);
        } else {
            txtNomeCurso.setText(curso.getNome());
            txtCargaHoraria.setText(String.valueOf(curso.getCargaHoraria()));
            txtValorCurso.setText(String.valueOf(curso.getValor()));
            txtProgramaCurso.setText(curso.getPrograma());
            frmtdtxtDtVigencia.setText(curso.getDtVigencia());
            txtValHrInstrutor.setText(String.valueOf(curso.getValHrInstrutor()));

            txtSiglaCurso.setEnabled(false);
            txtNomeCurso.setEnabled(true);
            txtNomeCurso.requestFocus();
            txtCargaHoraria.setEnabled(true);
            txtValorCurso.setEnabled(true);
            txtProgramaCurso.setEnabled(true);
            frmtdtxtDtVigencia.setEnabled(true);
            txtValHrInstrutor.setEnabled(true);

            btnConsultar.setEnabled(false);
            btnInserir.setEnabled(true);
            btnAlterar.setEnabled(true);
            btnExcluir.setEnabled(true);
            btnSair.setEnabled(true);
        }


    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        curso = new Curso(txtSiglaCurso.getText(), txtNomeCurso.getText());

        curso.setCargaHoraria(Integer.parseInt(txtCargaHoraria.getText()));
        curso.setValor(Double.parseDouble(txtValorCurso.getText()));
        curso.setPrograma(txtProgramaCurso.getText());
        curso.setDataVigencia(frmtdtxtDtVigencia.getText());
        curso.setValHrInstrutor(Double.parseDouble(txtValHrInstrutor.getText()));
        daoCurso.inserir(curso);

        txtSiglaCurso.setText("");
        txtNomeCurso.setText("");
        txtCargaHoraria.setText("");
        txtValorCurso.setText("");
        txtProgramaCurso.setText("");
        frmtdtxtDtVigencia.setText("");
        txtValHrInstrutor.setText("");

        txtSiglaCurso.setEnabled(true);
        txtNomeCurso.setEnabled(false);
        txtCargaHoraria.setEnabled(false);
        txtValorCurso.setEnabled(false);
        txtProgramaCurso.setEnabled(false);
        frmtdtxtDtVigencia.setEnabled(false);
        txtValHrInstrutor.setEnabled(false);
        txtSiglaCurso.requestFocus();

        btnInserir.setEnabled(false);
        btnConsultar.setEnabled(true);
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Alteração?") == 0) {//Sim
            curso.setNome(txtNomeCurso.getText());
            curso.setCargaHoraria(Integer.parseInt(txtCargaHoraria.getText()));
            curso.setValor(Double.parseDouble(txtValorCurso.getText()));
            curso.setDataVigencia(frmtdtxtDtVigencia.getText());
            curso.setValHrInstrutor(Double.parseDouble(txtValHrInstrutor.getText()));            
            curso.setPrograma(txtProgramaCurso.getText());          
            daoCurso.alterar(curso);
        }

        txtSiglaCurso.setText("");
        txtNomeCurso.setText("");
        txtCargaHoraria.setText("");
        txtValorCurso.setText("");
        txtProgramaCurso.setText("");
        frmtdtxtDtVigencia.setText("");
        txtValHrInstrutor.setText("");

        txtSiglaCurso.setEnabled(true);
        txtNomeCurso.setEnabled(false);
        txtCargaHoraria.setEnabled(false);
        txtValorCurso.setEnabled(false);
        txtProgramaCurso.setEnabled(false);
        frmtdtxtDtVigencia.setEnabled(false);
        txtValHrInstrutor.setEnabled(false);
        txtSiglaCurso.requestFocus();

        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Exclusão?") == 0) {
            daoCurso.excluir(curso);

            txtSiglaCurso.setText("");
            txtNomeCurso.setText("");
            txtCargaHoraria.setText("");
            txtValorCurso.setText("");
            txtProgramaCurso.setText("");
            frmtdtxtDtVigencia.setText("");
            txtValHrInstrutor.setText("");

            txtSiglaCurso.setEnabled(true);
            txtNomeCurso.setEnabled(false);
            txtCargaHoraria.setEnabled(false);
            txtValorCurso.setEnabled(false);
            txtProgramaCurso.setEnabled(false);
            frmtdtxtDtVigencia.setEnabled(false);
            txtValHrInstrutor.setEnabled(false);
            txtSiglaCurso.requestFocus();

            btnConsultar.setEnabled(true);
            btnInserir.setEnabled(false);
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiCurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.JFormattedTextField frmtdtxtDtVigencia;
    private javax.swing.JLabel lblCargaHoraria;
    private javax.swing.JLabel lblDtVigencia;
    private javax.swing.JLabel lblNomeCurso;
    private javax.swing.JLabel lblProgramaCurso;
    private javax.swing.JLabel lblSiglaCurso;
    private javax.swing.JLabel lblValorCurso;
    private javax.swing.JLabel lblVarHrInstrutor;
    private javax.swing.JTextField txtCargaHoraria;
    private javax.swing.JTextField txtNomeCurso;
    private javax.swing.JTextField txtProgramaCurso;
    private javax.swing.JTextField txtSiglaCurso;
    private javax.swing.JTextField txtValHrInstrutor;
    private javax.swing.JTextField txtValorCurso;
    // End of variables declaration//GEN-END:variables
    private Conexao conexao = null;
    private DaoCurso daoCurso = null;
    private Curso curso = null;
}
