/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.View;

import fatec.poo.control.Conexao;
import fatec.poo.control.DaoInstrutor;
import fatec.poo.model.Instrutor;
import javax.swing.JOptionPane;

/**
 * Felipe Camargo RA: 0030481813029 Vinicius Bistão RA: 0030481813011
 */
public class GuiInstrutor extends javax.swing.JFrame {

    /**
     * Creates new form GuiInstrutor
     */
    public GuiInstrutor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxEstadoCivil = new javax.swing.JComboBox<>();
        txtEndereco = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        frmtdtxtRG = new javax.swing.JFormattedTextField();
        btnSair1 = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();
        lblNum = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();
        txtNumero = new javax.swing.JTextField();
        btnInserir = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        lblCPF = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        frmtdtxtDtNasc = new javax.swing.JFormattedTextField();
        lblRG = new javax.swing.JLabel();
        lblDtNasc = new javax.swing.JLabel();
        frmtdtxtCPF = new javax.swing.JFormattedTextField();
        cbxSexo = new javax.swing.JComboBox<>();
        lblEstadoCivil = new javax.swing.JLabel();
        lblCPF1 = new javax.swing.JLabel();
        frmtdtxtCEP = new javax.swing.JFormattedTextField();
        lblTelRes = new javax.swing.JLabel();
        frmtdtxtTelRes = new javax.swing.JFormattedTextField();
        lblCelular = new javax.swing.JLabel();
        frmtdtxtCelular = new javax.swing.JFormattedTextField();
        txtFormacao = new javax.swing.JTextField();
        lblFormacao = new javax.swing.JLabel();
        lblAreaAtu = new javax.swing.JLabel();
        txtAreaAtu = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        cbxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro", "Casado" }));
        cbxEstadoCivil.setEnabled(false);
        cbxEstadoCivil.setName("cbxEstadoCivil"); // NOI18N

        txtEndereco.setEnabled(false);
        txtEndereco.setName("txtEndereco"); // NOI18N

        txtBairro.setEnabled(false);
        txtBairro.setName("txtBairro"); // NOI18N

        txtCidade.setEnabled(false);
        txtCidade.setName("txtCidade"); // NOI18N

        try {
            frmtdtxtRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        frmtdtxtRG.setEnabled(false);
        frmtdtxtRG.setName("frmtdtxtRG"); // NOI18N

        btnSair1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/View/icon/exit.png"))); // NOI18N
        btnSair1.setText("Sair");
        btnSair1.setName("btnSair"); // NOI18N
        btnSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair1ActionPerformed(evt);
            }
        });

        txtEmail.setEnabled(false);
        txtEmail.setName("txtEmail"); // NOI18N

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/View/icon/rem.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.setName("btnExcluir"); // NOI18N
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        lblNum.setText("Nº");
        lblNum.setName("lblNum"); // NOI18N

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/View/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.setName("btnAlterar"); // NOI18N
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        txtNumero.setEnabled(false);
        txtNumero.setName("txtNumero"); // NOI18N

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/View/icon/add.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.setName("btnInserir"); // NOI18N
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/View/icon/pesq.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.setName("btnConsultar"); // NOI18N
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        lblCPF.setText("CPF");
        lblCPF.setName("lblCPF"); // NOI18N

        lblNome.setText("Nome");
        lblNome.setName("lblNome"); // NOI18N

        lblEmail.setText("Email");
        lblEmail.setName("lblEmail"); // NOI18N

        lblSexo.setText("Sexo");
        lblSexo.setName("lblSexo"); // NOI18N

        lblEndereco.setText("Endereço");
        lblEndereco.setName("lblEndereco"); // NOI18N

        lblBairro.setText("Bairro");
        lblBairro.setName("lblBairro"); // NOI18N

        txtNome.setEnabled(false);
        txtNome.setName("txtNome"); // NOI18N

        lblCidade.setText("Cidade");
        lblCidade.setName("lblCidade"); // NOI18N

        try {
            frmtdtxtDtNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        frmtdtxtDtNasc.setEnabled(false);
        frmtdtxtDtNasc.setName("frmtdtxtDtNasc"); // NOI18N

        lblRG.setText("RG");
        lblRG.setName("lblRG"); // NOI18N

        lblDtNasc.setText("Data Nasc.");
        lblDtNasc.setName("lblDtNasc"); // NOI18N

        try {
            frmtdtxtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        frmtdtxtCPF.setName("frmtdtxtCPF"); // NOI18N

        cbxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        cbxSexo.setEnabled(false);
        cbxSexo.setName("cbxSexo"); // NOI18N

        lblEstadoCivil.setText("Estado Civil");
        lblEstadoCivil.setName("lblEstadoCivil"); // NOI18N

        lblCPF1.setText("CEP");
        lblCPF1.setName("lblCPF"); // NOI18N

        try {
            frmtdtxtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        frmtdtxtCEP.setEnabled(false);
        frmtdtxtCEP.setName("frmtdtxtCEP"); // NOI18N

        lblTelRes.setText("Tel. Res.");
        lblTelRes.setName("lblTelRes"); // NOI18N

        try {
            frmtdtxtTelRes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        frmtdtxtTelRes.setEnabled(false);
        frmtdtxtTelRes.setName("frmtdtxtTelRes"); // NOI18N

        lblCelular.setText("Celular");
        lblCelular.setName("lblCelular"); // NOI18N

        try {
            frmtdtxtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        frmtdtxtCelular.setEnabled(false);
        frmtdtxtCelular.setName("frmtdtxtCelular"); // NOI18N

        txtFormacao.setEnabled(false);
        txtFormacao.setName("txtFormacao"); // NOI18N

        lblFormacao.setText("Formação");
        lblFormacao.setName("lblFormacao"); // NOI18N

        lblAreaAtu.setText("Área de Atuação");
        lblAreaAtu.setName("lblAreaAtu"); // NOI18N

        txtAreaAtu.setEnabled(false);
        txtAreaAtu.setName("txtAreaAtu"); // NOI18N

        lblEstado.setText("Estado");
        lblEstado.setName("lblEstado"); // NOI18N

        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cbxEstado.setEnabled(false);
        cbxEstado.setName("cbxEstado"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblSexo)
                        .addGap(18, 18, 18)
                        .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(lblEstadoCivil)
                        .addGap(18, 18, 18)
                        .addComponent(cbxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEndereco)
                        .addGap(18, 18, 18)
                        .addComponent(txtEndereco)
                        .addGap(94, 94, 94)
                        .addComponent(lblNum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNome)
                            .addComponent(lblCPF))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDtNasc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(frmtdtxtDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(frmtdtxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEmail)
                                .addGap(18, 18, 18)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConsultar)
                                .addGap(6, 6, 6)
                                .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btnSair1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblRG)
                                .addGap(18, 18, 18)
                                .addComponent(frmtdtxtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCelular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(frmtdtxtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblAreaAtu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAreaAtu, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblFormacao)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(lblCidade)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblEstado)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(lblBairro)
                                .addGap(18, 18, 18)
                                .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblTelRes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(frmtdtxtTelRes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(lblCPF1)
                                .addGap(18, 18, 18)
                                .addComponent(frmtdtxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblCPF))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(frmtdtxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addComponent(lblDtNasc)))
                    .addComponent(frmtdtxtDtNasc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSexo)
                            .addComponent(lblEstadoCivil))))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEndereco)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblNum)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frmtdtxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBairro)
                            .addComponent(lblCPF1))))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCidade)
                        .addComponent(lblEstado)
                        .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(frmtdtxtTelRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTelRes)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblRG))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(frmtdtxtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(frmtdtxtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCelular)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFormacao)
                    .addComponent(txtAreaAtu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAreaAtu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultar)
                    .addComponent(btnInserir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair1))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao("SYSTEM", "123");
        conexao.setDriver("oracle.jdbc.driver.OracleDriver");
        conexao.setConnectionString("jdbc:oracle:thin:@localhost:1521:xe");
        daoInstrutor = new DaoInstrutor(conexao.conectar());
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        conexao.fecharConexao();
        dispose();
    }//GEN-LAST:event_formWindowClosed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        instrutor = null;
        instrutor = daoInstrutor.consultar(frmtdtxtCPF.getText());

        if (instrutor == null) {
            frmtdtxtCPF.setEnabled(false);
            txtNome.setEnabled(true);
            frmtdtxtDtNasc.setEnabled(true);
            cbxSexo.setEnabled(true);
            cbxEstadoCivil.setEnabled(true);
            txtEndereco.setEnabled(true);
            txtNumero.setEnabled(true);
            txtBairro.setEnabled(true);
            frmtdtxtCEP.setEnabled(true);
            txtCidade.setEnabled(true);
            cbxEstado.setEnabled(true);
            frmtdtxtTelRes.setEnabled(true);
            frmtdtxtRG.setEnabled(true);
            frmtdtxtCelular.setEnabled(true);
            txtEmail.setEnabled(true);
            txtNome.requestFocus();
            txtFormacao.setEnabled(true);
            txtAreaAtu.setEnabled(true);

            btnConsultar.setEnabled(false);
            btnInserir.setEnabled(true);
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);
        } else {
            txtNome.setText(instrutor.getNome());
            frmtdtxtDtNasc.setText(instrutor.getDtNasc());
            cbxSexo.setSelectedItem(instrutor.getSexo());
            cbxEstadoCivil.setSelectedItem(instrutor.getEstadoCivil());
            txtEndereco.setText(instrutor.getEndereco());
            txtNumero.setText(Integer.toString(instrutor.getNumero()));
            txtBairro.setText(instrutor.getBairro());
            frmtdtxtCEP.setText(instrutor.getCep());
            txtCidade.setText(instrutor.getCidade());
            cbxEstado.setSelectedItem(instrutor.getEstado());
            frmtdtxtTelRes.setText(instrutor.getTelRes());
            frmtdtxtRG.setText(instrutor.getRg());
            frmtdtxtCelular.setText(instrutor.getCelular());
            txtEmail.setText(instrutor.getEmail());
            txtFormacao.setText(instrutor.getFormacao());
            txtAreaAtu.setText(instrutor.getAreaAtu());
            txtNome.requestFocus();

            frmtdtxtCPF.setEnabled(false);
            txtNome.setEnabled(true);
            frmtdtxtDtNasc.setEnabled(true);
            cbxSexo.setEnabled(true);
            cbxEstadoCivil.setEnabled(true);
            txtEndereco.setEnabled(true);
            txtNumero.setEnabled(true);
            txtBairro.setEnabled(true);
            frmtdtxtCEP.setEnabled(true);
            txtCidade.setEnabled(true);
            cbxEstado.setEnabled(true);
            frmtdtxtTelRes.setEnabled(true);
            frmtdtxtRG.setEnabled(true);
            frmtdtxtCelular.setEnabled(true);
            txtEmail.setEnabled(true);
            txtFormacao.setEnabled(true);
            txtAreaAtu.setEnabled(true);
            txtNome.requestFocus();

            btnConsultar.setEnabled(false);
            btnInserir.setEnabled(false);
            btnAlterar.setEnabled(true);
            btnExcluir.setEnabled(true);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        instrutor = new Instrutor(frmtdtxtCPF.getText(), txtNome.getText());

        instrutor.setDtNasc(frmtdtxtDtNasc.getText());
        instrutor.setSexo(String.valueOf(cbxSexo.getSelectedItem()));
        instrutor.setEstadoCivil(String.valueOf(cbxEstadoCivil.getSelectedItem()));
        instrutor.setEndereco(txtEndereco.getText());
        instrutor.setNumero(Integer.parseInt(txtNumero.getText()));
        instrutor.setBairro(txtBairro.getText());
        instrutor.setCep(frmtdtxtCEP.getText());
        instrutor.setCidade(txtCidade.getText());
        instrutor.setEstado(String.valueOf(cbxEstado.getSelectedItem()));
        instrutor.setTelRes(frmtdtxtTelRes.getText());
        instrutor.setRg(frmtdtxtRG.getText());
        instrutor.setCelular(frmtdtxtCelular.getText());
        instrutor.setEmail(txtEmail.getText());
        instrutor.setFormacao(txtFormacao.getText());
        instrutor.setAreaAtu(txtAreaAtu.getText());
        daoInstrutor.inserir(instrutor);

        frmtdtxtCPF.setText("");
        txtNome.setText("");
        frmtdtxtDtNasc.setText("");
        cbxSexo.setSelectedItem("");
        cbxEstadoCivil.setSelectedItem("");
        txtEndereco.setText("");
        txtNumero.setText("");
        txtBairro.setText("");
        frmtdtxtCEP.setText("");
        txtCidade.setText("");
        cbxEstado.setSelectedItem("");
        frmtdtxtTelRes.setText("");
        frmtdtxtRG.setText("");
        frmtdtxtCelular.setText("");
        txtEmail.setText("");
        txtFormacao.setText("");
        txtAreaAtu.setText("");

        frmtdtxtCPF.setEnabled(true);
        txtNome.setEnabled(false);
        frmtdtxtDtNasc.setEnabled(false);
        cbxSexo.setEnabled(false);
        cbxEstadoCivil.setEnabled(false);
        txtEndereco.setEnabled(false);
        txtNumero.setEnabled(false);
        txtBairro.setEnabled(false);
        frmtdtxtCEP.setEnabled(false);
        txtCidade.setEnabled(false);
        cbxEstado.setEnabled(false);
        frmtdtxtTelRes.setEnabled(false);
        frmtdtxtRG.setEnabled(false);
        frmtdtxtCelular.setEnabled(false);
        txtEmail.setEnabled(false);
        txtFormacao.setEnabled(false);
        txtAreaAtu.setEnabled(false);
        frmtdtxtCPF.requestFocus();

        btnInserir.setEnabled(false);
        btnConsultar.setEnabled(true);
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Alteração?") == 0) {//Sim
            instrutor.setNome(txtNome.getText());
            instrutor.setDtNasc(frmtdtxtDtNasc.getText());
            instrutor.setSexo(String.valueOf(cbxSexo.getSelectedItem()));
            instrutor.setEstadoCivil(String.valueOf(cbxEstadoCivil.getSelectedItem()));
            instrutor.setEndereco(txtEndereco.getText());
            instrutor.setNumero(Integer.parseInt(txtNumero.getText()));
            instrutor.setBairro(txtBairro.getText());
            instrutor.setCep(frmtdtxtCEP.getText());
            instrutor.setCidade(txtCidade.getText());
            instrutor.setEstado(String.valueOf(cbxEstado.getSelectedItem()));
            instrutor.setTelRes(frmtdtxtTelRes.getText());
            instrutor.setRg(frmtdtxtRG.getText());
            instrutor.setCelular(frmtdtxtCelular.getText());
            instrutor.setEmail(txtEmail.getText());
            instrutor.setFormacao(txtFormacao.getText());
            instrutor.setAreaAtu(txtAreaAtu.getText());
            daoInstrutor.alterar(instrutor);
        }

        frmtdtxtCPF.setText("");
        txtNome.setText("");
        frmtdtxtDtNasc.setText("");
        cbxSexo.setSelectedItem("");
        cbxEstadoCivil.setSelectedItem("");
        txtEndereco.setText("");
        txtNumero.setText("");
        txtBairro.setText("");
        frmtdtxtCEP.setText("");
        txtCidade.setText("");
        cbxEstado.setSelectedItem("");
        frmtdtxtTelRes.setText("");
        frmtdtxtRG.setText("");
        frmtdtxtCelular.setText("");
        txtEmail.setText("");
        txtFormacao.setText("");
        txtAreaAtu.setText("");

        frmtdtxtCPF.setEnabled(true);
        txtNome.setEnabled(false);
        frmtdtxtDtNasc.setEnabled(false);
        cbxSexo.setEnabled(false);
        cbxEstadoCivil.setEnabled(false);
        txtEndereco.setEnabled(false);
        txtNumero.setEnabled(false);
        txtBairro.setEnabled(false);
        frmtdtxtCEP.setEnabled(false);
        txtCidade.setEnabled(false);
        cbxEstado.setEnabled(false);
        frmtdtxtTelRes.setEnabled(false);
        frmtdtxtRG.setEnabled(false);
        frmtdtxtCelular.setEnabled(false);
        txtEmail.setEnabled(false);
        txtFormacao.setEnabled(false);
        txtAreaAtu.setEnabled(false);
        frmtdtxtCPF.requestFocus();

        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Exclusão?") == 0) {
            daoInstrutor.excluir(instrutor);

            frmtdtxtCPF.setText("");
            txtNome.setText("");
            frmtdtxtDtNasc.setText("");
            cbxSexo.setSelectedItem("");
            cbxEstadoCivil.setSelectedItem("");
            txtEndereco.setText("");
            txtNumero.setText("");
            txtBairro.setText("");
            frmtdtxtCEP.setText("");
            txtCidade.setText("");
            cbxEstado.setSelectedItem("");
            frmtdtxtTelRes.setText("");
            frmtdtxtRG.setText("");
            frmtdtxtCelular.setText("");
            txtEmail.setText("");
            txtFormacao.setText("");
            txtAreaAtu.setText("");

            frmtdtxtCPF.setEnabled(true);
            txtNome.setEnabled(false);
            frmtdtxtDtNasc.setEnabled(false);
            cbxSexo.setEnabled(false);
            cbxEstadoCivil.setEnabled(false);
            txtEndereco.setEnabled(false);
            txtNumero.setEnabled(false);
            txtBairro.setEnabled(false);
            frmtdtxtCEP.setEnabled(false);
            txtCidade.setEnabled(false);
            cbxEstado.setEnabled(false);
            frmtdtxtTelRes.setEnabled(false);
            frmtdtxtRG.setEnabled(false);
            frmtdtxtCelular.setEnabled(false);
            txtEmail.setEnabled(false);
            txtFormacao.setEnabled(false);
            txtAreaAtu.setEnabled(false);
            frmtdtxtCPF.requestFocus();

            btnConsultar.setEnabled(true);
            btnInserir.setEnabled(false);
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSair1ActionPerformed
        dispose();
    }//GEN-LAST:event_btnSair1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiInstrutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair1;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JComboBox<String> cbxEstadoCivil;
    private javax.swing.JComboBox<String> cbxSexo;
    private javax.swing.JFormattedTextField frmtdtxtCEP;
    private javax.swing.JFormattedTextField frmtdtxtCPF;
    private javax.swing.JFormattedTextField frmtdtxtCelular;
    private javax.swing.JFormattedTextField frmtdtxtDtNasc;
    private javax.swing.JFormattedTextField frmtdtxtRG;
    private javax.swing.JFormattedTextField frmtdtxtTelRes;
    private javax.swing.JLabel lblAreaAtu;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCPF1;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblDtNasc;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblFormacao;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelRes;
    private javax.swing.JTextField txtAreaAtu;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtFormacao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
    private Conexao conexao = null;
    private DaoInstrutor daoInstrutor = null;
    private Instrutor instrutor = null;
}
